config/routes.rb
Navigator2::Application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions"}
  devise_scope :user do
    get '/register', :to => 'registrations#new'
    get '/login', :to => 'sessions#new'
    get '/logout', :to => 'sessions#destroy'
    resources :sessions
  end

  
  #devise_scope :admin_user do
#    resources :sessions
  #end

  root :to => "home#index"
  match '/sitemap' => 'home#sitemap'  
  resources :items
  match 'admin' => 'admin::Pages#index'
  
  devise_for :admin_users, :controllers => { :sessions => "admin/sessions" }, :path_prefix => :admin
  devise_scope :admin_user do
    resources :sessions, :controller => "admin/sessions"
  end
  
  namespace "admin" do
    
    match 'sort/:model' => 'sort#sort'
    match 'typograph/typograph' => 'typograph#typograph'
    resources :pages do
      member do
        get 'menu'
        get 'hide'
      end
    end
    resources :items, :used_items, :hints, :blogs, :comments do
      member do
        get 'menu'
      end
    end
    resources :users do
      member do
        get 'menu'
      end
      collection do
        get 'notifications'
        get 'notification'
        post 'send_notification'
      end
    end
    resources :item_properties, :assets, :asset_groups, :banners, :properties, :slides
    resources :blocks
    resources :posts do 
      member do
        get 'menu'  
      end
    end
  end
  

  resources :posts
  resources :hints do
    member do
      get 'next'
    end
  end
  resources :assets
  resources :users do
    resources :blogs
    resource :resume
    resource :item
    member do
      get 'sell_yacht'
      get 'pagestyle'
      get 'personal'
    end

  end
  resources :pages, :controller => :home
#  match '/javascripts/*path' => Sprockets
#  match '/gallery' => 'gallery#index'
  #devise_for :users
  
  
  match '/catalog' => 'catalog#main'
  match '/catalog/s_probegom' => 'catalog#used'
#  match '/catalog/s_probegom/:sort' => 'catalog#used'
  match '/filter' => 'selection#index'
  match '/filter/do' => 'selection#list'
  match '/filter/search' => 'selection#search'
  match '/comparison' => 'comparison#index'
  match '/comparison/pdf' => 'comparison#pdf'
  match '/comparison/:id' => 'comparison#add'
=begin
  Page.all.each do |page|
    unless page.resource
      get page.url => 'home#show', :id => page.id
    else
      get page.url => page.resource.sub('/', '#'), :id => page.id
      get page.url+'/:id' => 'catalog#show'
    end
  end
=end
#  match 'ckeditor/:action(/:id(.:format))' => 'ckeditor'
  namespace :ckeditor do
    resources :pictures, :only => [:index, :create, :destroy]
    resources :attachments, :only => [:index, :create, :destroy]
  end
  
  resources :resumes 

  
  
  resources :blogs do
    collection do
      get 'topics/:topic_id' => 'blogs#topics'
      get 'tags/:tag' => 'blogs#tags'
      get 'tag/:tag' => 'blogs#tags'
      get 'admin_posts'
      get 'member_posts'
    end
#    get 'member_posts'
    resources :comments
  end
  
  match '/about/news' => 'posts#index'
  match '/about/news/:id' => 'posts#show'
  match '/about/sudovladelcu' => 'home#owner'
  match '/about/kapitanu' => 'home#captain'
  match '/about/captain' => 'home#captain'
  match '/about/resume' => 'resumes#index'
  match '/about/resumes' => 'resumes#index'
  match '/about/members' => 'members#index'
  match '/messages/:action(/:id)' => 'messages'
#  match ':controller/:action(/:id(.:format))'
  match '*path' => 'redirect#index'
end

app/controllers/admin/used_items_controller.rb
class Admin::UsedItemsController < Admin::BaseController
  inherit_resources
  respond_to :html, :xml, :json
  defaults :route_prefix => 'admin'
 
  def new
    @item = Item.new
#    @item.assets.build
    @item.item_properties.build
  end
  
  def create
    create!(:notice => "Dude! Nice job creating that page. Yeeeah") { collection_url }
  end
  
  def update
    update!(:notice => "Dude! Nice job creating that page. Yeeeah") { collection_url }
  end
  
  def menu
    render :partial => 'menu'
  end
  
  protected
  
  def resource
    @item = Item.unscoped.find(params[:id])
  end
  def collection
    if params[:page_id]
        @items = Item.unscoped.where(:page_id => params[:page_id]).all
      else
        @items = Item.unscoped.where("page_id = 10").all
    end
  end
end

app/helpers/admin/used_items_helper.rb
module Admin::UsedItemsHelper
end

app/views/admin/used_items/_asset_fields.html.erb
<div class="fields">
<% f.inputs do %>
  <%= f.input :asset, :as => :file, :name => :filename, :label => "Файл" %>
  <%= f.hidden_field :asset_group_id, :value => @asset_group_id %>
  <%#= f.input :asset_group, :as => :select %>      

  <%= link_to_remove_fields("Удалить", f)%>
<% end %>
</div>

app/views/admin/used_items/_form.html.erb
<% #coding: utf-8 %>
<%= semantic_form_for ["admin", @item], :html => { :multipart => true } do |f| %>
  <% @item.errors.each do |field,error| %>
    <b><%= field %> <%= error %></b><br/>
  <% end %>
  <%= f.inputs do %>
    <%= f.input :page_id, :value => Page.find_by_slug("s_probegom").id, :as => :hidden %>
	<%= f.input :title %>
	<%= f.input :price %> <%= f.input :currency, :label => "Валюта" %>
	<%= f.input :user, :label => "Пользователь", :as => :select %>
	<%= f.input :item_assign, :as => :select, :label => "Назначение" %>
	<%= f.input :lgth, :label => "Длина" %>
	<li id="item_on_hand_input" class="boolean optional"><label for="item_on_hand">Есть в наличии</label><%= f.check_box :on_hand %></li>
	<li id="item_description_input" class="string optional">
		<label for="item_description">Описание</label>
		<div class="left"><%= f.ckeditor_textarea :item, :description %></div>
	</li>

      <%= f.input :mileage, :label => "Пробег" %>
      <%= f.input :year, :label => "Год выпуска" %>

	<%= f.semantic_fields_for :image do |image_form| %>
	  <%= image_tag @item.image.url(:thumb) if @item.image %>
	  <%= image_form.input :attachment, :as => :file %>
      <%#= f.input :remove_image, :as => :boolean, :label => "Удалить картинку" %>
       <%= link_to_remove_fields "Удалить", image_form %>
    <% end %>
    <% #f.inputs :for => :assets %>
   <% end %>

    <%= f.inputs do %>
	<a class="collapse" href="javascript:void();" rel="gallery_block">Галерея</a>
	<div class="gallery_block hidden">
	<% if @item.gallery_images %>
	 <% @item.gallery_images.each do |image| %>
	    <div id="<%= dom_id(image) %>"><%= image_tag image.url(:thumb) %> <%= link_to "Удалить", admin_asset_path(image, :js), :method => :delete, :confirm => "Удалить файл?", :remote => true %></div>
	  <% end %>
	<% end %>
	<% f.semantic_fields_for :gallery_images do |gallery_images| %>
     <%#= render 'interior_images', :f => interior_images %>
	<% end %>
	<%= link_to_add_fields "Добавить", f, :gallery_images %>
	</div>
   <% end %>

   <%= f.inputs do %>
	<a class="collapse" href="javascript:void();" rel="properties_block">Характеристики</a>
	<div class="properties_block hidden">
	<%= f.semantic_fields_for :item_properties do |item_properties| %>
      <%= render 'item_property_fields', :f => item_properties %>
	<% end %>
	
	<%= link_to_add_fields "Добавить", f, :item_properties %>
	</div>
   <% end %>
	<%= f.buttons do %>
	  <%= f.commit_button :label => "Сохранить", :button_html => {:class => :yellow_button} %>
	  <li><%= link_to "Отменить", "", :class => :yellow_button, :confirm => "Внимание!\nИзменения не будут сохранены. Продолжить?" %></li>
	<% end %>
<% end %>

app/views/admin/used_items/_gallery_image_field.html.erb
<div class="fields">
<%= f.inputs do %>
  <%= f.input :attachment, :as => :file, :label => "Файл" %>
  <%#= f.hidden_field :asset_group_id, :value => @asset_group_id %>
  <%#= f.input :asset_group, :as => :select %>      

  <%= link_to_remove_fields("Удалить", f)%>
<% end %>
</div>

app/views/admin/used_items/_gallery_image_fields.html.erb
<div class="fields">
<%= f.inputs do %>
  <%= f.input :attachment, :as => :file, :label => "Файл" %>
  <%#= f.hidden_field :asset_group_id, :value => @asset_group_id %>
  <%#= f.input :asset_group, :as => :select %>      

  <%= link_to_remove_fields("Удалить", f)%>
<% end %>
</div>

app/views/admin/used_items/_item_property_fields.html.erb
<% content_tag(:div, :class => "fields properties") do %>
<% f.inputs do %>
<%= f.input :property, :as => :select, :class => :property %> <%#= link_to "Новое свойство", new_admin_property_path, {:remote => true} %>
<%= f.input :value %> 
<%= link_to_remove_fields("Удалить", f) %>  
<% end %>
<% end %>

app/views/admin/used_items/_menu.html.erb
<ul class="contextMenu">
<li class="arrow"></li>
<li><a class="ico_cmEdit" href="<%= edit_resource_url(resource) %>">Редактировать</a></li>
<% if resource.methods.find{|m| m=="status"} %><li><a class="ico_cmHide" href="<%= hide_resource_url(resource) %>">Режим невидимости</a></li><% end %>
<% if resource.methods.find{|m| m=="resource"} && resource.resource == 'items' && resource.model_name == "Page" %><li><a class="ico_cmAdd" href="<%= new_item_url(resource, :page => resource) %>">Добавить товар</a></li><% end %>
<li><%= link_to "Удалить", resource_url(resource), :method => :delete, :class => "ico_cmDel" %></li>
<li class="close"><a href="javascript:void(0);">&times;</a></li>
</ul>

app/views/admin/used_items/edit.html.erb
<h2>Редактирование товара</h2>
<%= render 'form' %>

app/views/admin/used_items/index.html.erb
<% content_for :helpbar do %>
<div class="addItems_border">
<ul class="addItems">
	<li class="red"><%= link_to "Новый товар", new_resource_url  %></li>
    <li><%#= link_to 'Добавить новость', new_admin_post_path, :class => "ico_addArrow" %></li>
    
</ul>
</div>
<% end %>

<table border="0" id="main">
	<tr>
		<td>
			<ul class="tree other sortable" id="items">
				<% collection.each do |resource| %>
				<li id="item_<%= resource.id %>"><span><center><%= resource.title.to_s + " " + resource.lgth.to_s %><br/><% if resource.image %><%=image_tag(resource.image.url(:thumb)) %><% elsif resource.gallery_images.size > 0 %><%= image_tag(resource.gallery_images.first.url(:thumb))%><% end %></center>
				                <p class="buttons"><%= link_to "", resource_url(resource), :method => :delete, :class=> "ico_cmDel", :confirm => "Объект будет удален!\nХотите продолжить?" %><a class="ico_cmEdit" href="<%=edit_resource_url(resource)%>"></a></p>
				                </span></li>
				<% end %>
			</ul>
		</td>
	</tr>
</table>

app/views/admin/used_items/new.html.erb
<h2>Новый товар</h2>
<%= render 'form' %>