config/routes.rb
Navigator2::Application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions"}
  devise_scope :user do
    get '/register', :to => 'registrations#new'
    get '/login', :to => 'sessions#new'
    get '/logout', :to => 'sessions#destroy'
    resources :sessions
  end

  
  #devise_scope :admin_user do
#    resources :sessions
  #end

  root :to => "home#index"
  match '/sitemap' => 'home#sitemap'  
  resources :items
  match 'admin' => 'admin::Pages#index'
  
  devise_for :admin_users, :controllers => { :sessions => "admin/sessions" }, :path_prefix => :admin
  devise_scope :admin_user do
    resources :sessions, :controller => "admin/sessions"
  end
  
  namespace "admin" do
    
    match 'sort/:model' => 'sort#sort'
    match 'typograph/typograph' => 'typograph#typograph'
    resources :pages do
      member do
        get 'menu'
        get 'hide'
      end
    end
    resources :items, :used_items, :hints, :blogs, :comments do
      member do
        get 'menu'
      end
    end
    resources :users do
      member do
        get 'menu'
      end
      collection do
        get 'notifications'
        get 'notification'
        post 'send_notification'
      end
    end
    resources :item_properties, :assets, :asset_groups, :banners, :properties, :slides
    resources :blocks
    resources :posts do 
      member do
        get 'menu'  
      end
    end
  end
  

  resources :posts
  resources :hints do
    member do
      get 'next'
    end
  end
  resources :assets
  resources :users do
    resources :blogs
    resource :resume
    resource :item
    member do
      get 'sell_yacht'
      get 'pagestyle'
      get 'personal'
    end

  end
  resources :pages, :controller => :home
#  match '/javascripts/*path' => Sprockets
#  match '/gallery' => 'gallery#index'
  #devise_for :users
  
  
  match '/catalog' => 'catalog#main'
  match '/catalog/s_probegom' => 'catalog#used'
#  match '/catalog/s_probegom/:sort' => 'catalog#used'
  match '/filter' => 'selection#index'
  match '/filter/do' => 'selection#list'
  match '/filter/search' => 'selection#search'
  match '/comparison' => 'comparison#index'
  match '/comparison/pdf' => 'comparison#pdf'
  match '/comparison/:id' => 'comparison#add'
=begin
  Page.all.each do |page|
    unless page.resource
      get page.url => 'home#show', :id => page.id
    else
      get page.url => page.resource.sub('/', '#'), :id => page.id
      get page.url+'/:id' => 'catalog#show'
    end
  end
=end
#  match 'ckeditor/:action(/:id(.:format))' => 'ckeditor'
  namespace :ckeditor do
    resources :pictures, :only => [:index, :create, :destroy]
    resources :attachments, :only => [:index, :create, :destroy]
  end
  
  resources :resumes 

  
  
  resources :blogs do
    collection do
      get 'topics/:topic_id' => 'blogs#topics'
      get 'tags/:tag' => 'blogs#tags'
      get 'tag/:tag' => 'blogs#tags'
      get 'admin_posts'
      get 'member_posts'
    end
#    get 'member_posts'
    resources :comments
  end
  
  match '/about/news' => 'posts#index'
  match '/about/news/:id' => 'posts#show'
  match '/about/sudovladelcu' => 'home#owner'
  match '/about/kapitanu' => 'home#captain'
  match '/about/captain' => 'home#captain'
  match '/about/resume' => 'resumes#index'
  match '/about/resumes' => 'resumes#index'
  match '/about/members' => 'members#index'
  match '/messages/:action(/:id)' => 'messages'
#  match ':controller/:action(/:id(.:format))'
  match '*path' => 'redirect#index'
end

app/views/shared/_blog_left_menu.html.erb
	<ul class="leftMenu">
	<% if params[:action] == 'index' %>
	<li class="current"><p>Все записи<span>→</span></a></li>
	<% else %>
	<li><a href="/blogs/">Все записи<span>→</span></a></li>
	<% end %>
	<% if params[:action] == 'admin_posts' %>
	<li class="current"><p>Записи администрации<span>→</span></a></li>
	<% else %>	
	<li><a href="/blogs/admin_posts">Записи администрации<span>→</span></a></li>
	<% end %>
	<% if params[:action] == 'member_posts'%>
	<li class="current"><p>Записи членов клуба<span>→</span></a></li>
	<% else %>
	<li><a href="/blogs/member_posts">Записи членов клуба<span>→</span></a></li>
	<% end %>
	</ul>
	<div class="clear"><br /></div>
	<!--<h2>Категории</h2>-->
	<ul class="leftMenu" style="display:none;">
		<% BlogTopic.all.each do |topic| %>

	<li<%=raw ' class="current"' if params[:topic_id].to_i == topic.id %>><a href="/blogs/topics/<%= topic.id %>"><%= topic.title %><span>→</span></a></li>
	    <% end %>
	</ul>
	<% if current_user %>
	<div class="leftBlueBox">
		<% if current_user %><div><span class="blogPic"></span><a href="<%= new_blog_path %>"><span>Добавить запись в личный блог</span></a></div><% end %>
	</div>
	<% end %>

app/views/shared/_breadcrumbs.html.erb
<% 
@page ||= @item.page if @item
%>
<div class="tree">
<% if @item %>
	<a href="/">Главная</a><% @page.self_and_ancestors.each do |page| %> / <a href="<%= page.url %>"><%= strip_tags(page.title) %></a><% end %> <%= raw ' / ' + content_tag(:b, @item.title+" "+@item.lgth.to_s) if @item %>
<% else %>
<a href="/">Главная</a><% @page.self_and_ancestors.each do |page| %>
  <% if page == @page %>
   / <b><%= raw page.title %></b>
  <% else %>
   / <a href="<%= page.url %>"><%= strip_tags(page.title) %></a>
  <% end %>
<% end %>

<% end %>
	<div class="arrow"></div>
</div>
	<div class="clear"></div>

app/views/shared/_left_menu.html.erb
<ul class="leftMenu">
<% 
if @page.root?
  left_menu_items = @page.children.menu.order(:position)
else
  left_menu_items = @page.self_and_siblings.menu.order(:position)
end
%>

<% left_menu_items.each do |page| %>
  <%= raw link_or_span(page) %> 
<% end %>

</ul>
<% if current_user %>
<div class="leftBlueBox">
	<% if current_user.owner? %>
	<div><span class="resumePic"></span><a href="/about/resumes"><span>Резюме капитанов</span></a></div>
<!--	<div><span class="servisPic"></span><a href="<%= resumes_path %>"><span>Заявка на сервисное обслуживание яхты</span></a></div> -->
    <% end %>
    <% if current_user.captain? %>

	<% end %>
	<div><span class="blogPic"></span><a href="<%= new_user_blog_path(current_user) %>"><span>Добавить запись в личный блог</span></a></div>
</div>
<% end %>

<% if @page && (@page.attachments.size > 0) %>
	<ul class="files">
	<% if @page.attachments.size > 0 %>
	<% @page.attachments.each do |asset| %>
	<div class="file <%= asset.attachment_file_name.split(".").last.downcase %>"><a href="<%= asset.url %>"><%= asset.attachment_file_name %></a>
		<%= asset.attachment_file_name.split(".").last.upcase %>, <%= (asset.attachment_file_size/1024).round(3) %> Кб
		</div>
	<% end %>
	<% end %>
	</ul>
<% end %>

<% if @page && @page.blocks.size > 0 %>
<div class="clear"></div>
	<% @page.blocks.each do |block| %>
	<%= raw block.content %>
	<% end %>
<% end %>

app/views/shared/_menu.html.erb
<% Page.roots.menu.each do |page| %>

<li><a<%=raw ' class="current"' if request.fullpath.to_s.include?(page.slug) %> href="<%=page.url %>"><%= page.title %></a>
  <% if page.slug == 'catalog' && page.children.menu.size > 0 %><span class="arrow"></span>
  <ul class="sub1">
	<% page.children.menu.order(:position).each do |child_page| %>
	<li><a href="<%= child_page.url %>"><%= child_page.title %></a>
		<% if child_page.items.size > 0 && child_page.slug != 's_probegom' %><span class="arrow"></span>
		<ul class="sub2">
			<% child_page.items.order(:position).each do |item| %>
			  <li class="yaht_load" id="<%=dom_id(item)%>"><a href="<%= item.url %>"><%= item.lgth.to_s + ' ' + item.title %></a><span class="arrow"></span>
				<%= render 'items/show', :item => item %>
				</li>
			<% end %>
		</ul>
		<% end %>
	</li>
	<% end %>
  </ul>
  <% end %>	
</li>
<% end %>

app/views/shared/_user_tabs.html.erb
<ul class="tabs blue">
	<li<%=raw ' class="current"' if (params[:action] == 'show' || params[:action] == 'edit') && (params[:controller] == 'registrations' || params[:controller] == 'users') %>><a href="<%= edit_registration_path(current_user) %>">Основное</a></li>
	<% if current_user.owner? %><li<%=raw ' class="current"' if params[:controller] == 'items' %>><a href="<%= edit_user_item_path(current_user) %>">Моя яхта</a></li><% end %>
	<% if current_user.captain? %>
	<% if current_user.resume %><li<%=raw ' class="current"' if params[:controller] == 'resumes' %>><a href="<%= user_resume_path(current_user) %>">Мое резюме</a></li>
	<% else %><li<%=raw ' class="current"' if params[:controller] == 'resumes' %>><a href="<%= new_user_resume_path(current_user) %>">Мое резюме</a></li>
	<% end %>
	<% end %>
	<li class="last"></li>
</ul>