config/routes.rb
Navigator2::Application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions"}
  devise_scope :user do
    get '/register', :to => 'registrations#new'
    get '/login', :to => 'sessions#new'
    get '/logout', :to => 'sessions#destroy'
    resources :sessions
  end

  
  #devise_scope :admin_user do
#    resources :sessions
  #end

  root :to => "home#index"
  match '/sitemap' => 'home#sitemap'  
  resources :items
  match 'admin' => 'admin::Pages#index'
  
  devise_for :admin_users, :controllers => { :sessions => "admin/sessions" }, :path_prefix => :admin
  devise_scope :admin_user do
    resources :sessions, :controller => "admin/sessions"
  end
  
  namespace "admin" do
    
    match 'sort/:model' => 'sort#sort'
    match 'typograph/typograph' => 'typograph#typograph'
    resources :pages do
      member do
        get 'menu'
        get 'hide'
      end
    end
    resources :items, :used_items, :hints, :blogs, :comments do
      member do
        get 'menu'
      end
    end
    resources :users do
      member do
        get 'menu'
      end
      collection do
        get 'notifications'
        get 'notification'
        post 'send_notification'
      end
    end
    resources :item_properties, :assets, :asset_groups, :banners, :properties, :slides
    resources :blocks
    resources :posts do 
      member do
        get 'menu'  
      end
    end
  end
  

  resources :posts
  resources :hints do
    member do
      get 'next'
    end
  end
  resources :assets
  resources :users do
    resources :blogs
    resource :resume
    resource :item
    member do
      get 'sell_yacht'
      get 'pagestyle'
      get 'personal'
    end

  end
  resources :pages, :controller => :home
#  match '/javascripts/*path' => Sprockets
#  match '/gallery' => 'gallery#index'
  #devise_for :users
  
  
  match '/catalog' => 'catalog#main'
  match '/catalog/s_probegom' => 'catalog#used'
#  match '/catalog/s_probegom/:sort' => 'catalog#used'
  match '/filter' => 'selection#index'
  match '/filter/do' => 'selection#list'
  match '/filter/search' => 'selection#search'
  match '/comparison' => 'comparison#index'
  match '/comparison/pdf' => 'comparison#pdf'
  match '/comparison/:id' => 'comparison#add'
=begin
  Page.all.each do |page|
    unless page.resource
      get page.url => 'home#show', :id => page.id
    else
      get page.url => page.resource.sub('/', '#'), :id => page.id
      get page.url+'/:id' => 'catalog#show'
    end
  end
=end
#  match 'ckeditor/:action(/:id(.:format))' => 'ckeditor'
  namespace :ckeditor do
    resources :pictures, :only => [:index, :create, :destroy]
    resources :attachments, :only => [:index, :create, :destroy]
  end
  
  resources :resumes 

  
  
  resources :blogs do
    collection do
      get 'topics/:topic_id' => 'blogs#topics'
      get 'tags/:tag' => 'blogs#tags'
      get 'tag/:tag' => 'blogs#tags'
      get 'admin_posts'
      get 'member_posts'
    end
#    get 'member_posts'
    resources :comments
  end
  
  match '/about/news' => 'posts#index'
  match '/about/news/:id' => 'posts#show'
  match '/about/sudovladelcu' => 'home#owner'
  match '/about/kapitanu' => 'home#captain'
  match '/about/captain' => 'home#captain'
  match '/about/resume' => 'resumes#index'
  match '/about/resumes' => 'resumes#index'
  match '/about/members' => 'members#index'
  match '/messages/:action(/:id)' => 'messages'
#  match ':controller/:action(/:id(.:format))'
  match '*path' => 'redirect#index'
end

app/controllers/home_controller.rb
#coding: utf-8
class HomeController < ApplicationController
  include ApplicationHelper
  in_place_edit_for :post, :title
  in_place_edit_for :item, :description
  in_place_edit_for :item, :announce
  in_place_edit_for :block, :content
  
  before_filter :find_page
  
  def set_post_title
        post = Post.find(params[:id]) 
        post.title = params[:value] # Name of parameter is always 'value'.
        post.save

        # It should render a text 
        render :text => post.title
  end
  
  def index
    @items = Item.brand_new.order("RAND()").limit(3)
    
    @posts = Post.order("updated_at DESC").limit(5)
    @blog_posts = BlogPost.order("updated_at DESC").limit(5)
    
    @page = Page.find_by_slug("main")
    @blocks = @page.blocks.limit(1) if @page
  end
  
  def show
    @page = Page.find_by_slug(params[:id])
    @page = Page.find(params[:id]) unless @page
  end
  
  def captain
    #render :text => query_string
    require 'pp'
    @g_spb = GoogleWeather.new('Saint-Petersburg')
#    require 'net/http'
#    require 'uri'

#       url = URI.parse('http://www.google.com/ig/api?weather=Moscow')
#        render :text => Net::HTTP.get_print(URI.parse('http://www.google.com/ig/api?weather=Moscow'))
#http = Net::HTTP.new
#http.start(url.host, url.port) { |http|
# response = http.post('http://www.google.com/ig/api', 'query=foo')
# }
# puts response.body       
        #req = Net::HTTP::Get.new(url.path)
        # res = Net::HTTP.start(url.host, url.port) {|http|
        #   http.request(req)
        # }
        # render :text => res.body, :format => :xml

#        res = Net::HTTP.start(url.host, url.port) {|http|
#          http.get('/ig/api/?weather=moscow')
#        }
#        render :text => res.body
    
    @g_msk = GoogleWeather.new('Moscow')
  end
  
  def owner
#    render :text => 
    @resumes = Resume.order(:created_at).limit(4).all
#        render :text => @resumes
  end

  
end

app/helpers/home_helper.rb
module HomeHelper
  
end

app/views/home/captain.html.erb
<% #coding: utf-8 %>
	<div class="w910 typical">
		<%= render 'shared/breadcrumbs' %>
		<div class="left">
			<%= render 'shared/left_menu' %>
		</div>
		<div class="right">
			<h1>Информация для капитана</h1>
			<div class="left col_2">
<%= raw @page.body %>
			</div>
			<div class="col_2 right">
				<% if @g_spb %>
				<h2>Санкт-Петербург</h2>
				
					<table class="b-current-weather"><tbody>
 						<tr><td class="t t8"><span><pre> <%= @g_spb.current_conditions.temp_c %>°C &nbsp;</pre></span><b><i></i></b></td><td class="i"><i class="b-wea-icon g-png"><img src="http://www.google.com<%=@g_spb.current_conditions.icon %>"></i></td><td class="f"><div></div><div><%= @g_spb.current_conditions.wind_condition.gsub("Wind", "Ветер").gsub("at", "~").gsub("N", "С").gsub("W", "З").gsub("E", "В").gsub("S", "Ю").gsub("mph", "м/с") %></div><div><%= @g_spb.current_conditions.humidity.gsub("Humidity", "Влажность") %></div></td></tr>
						</tbody></table>
						<table class="b-forecast-brief"><tbody>
							
							<tr><% @g_spb.forecast_conditions.each do |c| %><th class="t8"><%= t(c.day_of_week) %></th><% end %></tr>
						
							<tr class="data"><% @g_spb.forecast_conditions.each do |c| %><td class="t8"><b class="b-wea-icon g-png"><img src="http://www.google.com<%= c.icon %>"></b></td><% end %></tr>
							<tr class="data day"><% @g_spb.forecast_conditions.each do |c| %><td class="t8"><%= ((c.high.to_i-32)/1.8).to_i %>°</td><% end %>
							<tr class="data night"><% @g_spb.forecast_conditions.each do |c| %><td class="t6"><%= ((c.low.to_i-32)/1.8).to_i %>°</td><% end %></tr></tbody></table>
								<% end %>
								<% if @g_msk %>
								<h2>Москва</h2>

									<table class="b-current-weather"><tbody>
				 						<tr><td class="t t8"><span><pre> <%= @g_msk.current_conditions.temp_c %>°C &nbsp;</pre></span><b><i></i></b></td><td class="i"><i class="b-wea-icon g-png"><img src="http://www.google.com<%=@g_msk.current_conditions.icon %>"></i></td><td class="f"><div></div><div><%= @g_msk.current_conditions.wind_condition.gsub("Wind", "Ветер").gsub("at", "~").gsub("N", "С").gsub("W", "З").gsub("E", "В").gsub("S", "Ю").gsub("mph", "м/с") %></div><div><%= @g_msk.current_conditions.humidity.gsub("Humidity", "Влажность") %></div></td></tr>
										</tbody></table>
										<table class="b-forecast-brief"><tbody>

											<tr><% @g_msk.forecast_conditions.each do |c| %><th class="t8"><%= t(c.day_of_week) %></th><% end %></tr>

											<tr class="data"><% @g_msk.forecast_conditions.each do |c| %><td class="t8"><b class="b-wea-icon g-png"><img src="http://www.google.com<%= c.icon %>"></b></td><% end %></tr>
											<tr class="data day"><% @g_msk.forecast_conditions.each do |c| %><td class="t8"><%= ((c.high.to_i-32)/1.8).to_i %>°</td><% end %>
											<tr class="data night"><% @g_msk.forecast_conditions.each do |c| %><td class="t6"><%= ((c.low.to_i-32)/1.8).to_i %>°</td><% end %></tr></tbody></table>
												<% end %>
			</div>
			<%= render 'pages/attachments' %>
		</div>
	</div>
<% content_for :js do %>
<style type="text/css">
table.b-forecast-brief td, table.b-current-weather td { padding: 3px;}
table.b-current-weather td, table.b-current-weather div { word-wrap: pre;}
td.f { width: 100%;}
td.t6 { color: #999; font-size: 12px;}
table.b-forecast-brief { width: 230px;}
table.b-forecast-brief th, table.b-forecast-brief { text-align: center; }
</style>
<% end %>

app/views/home/index.html.erb
<div class="clear"></div>
<div class="main_banner">
	<div id="slider" class="images">
		<% if Slide.all.size > 0%>
		<% Slide.all.each do |slide| %>
			<%= image_tag slide.image.url, :title => slide.title, :alt => '', :href => slide.item.url, :style => 'display:none;' %>
		<% end %>
		<% end %>
	</div>

</div>

<div class="w910 index">
    	<div class="left">
        	<p class="about"><span></span><%= raw(sanitize @page.body, :tags => %w(a)) %></p>
            <h3>Яхты в <a href="/catalog">каталоге</a></h3>
            <ul class="cols_3">
	        <% @items.each do |item| %>
            <li id="item_<%= item.id %>">
            	<% if item.image %><a href="<%= item.url %>"><img src="<%= item.image.url(:thumb) %>" alt="" /></a><% end %>
                <p><a href="<%= item.item_url %>"><%= item.title %></a><br />
                	Длина: <%= item.lgth %> <%=Russian::p(item.lgth.to_i, "фут", "фута", "футов") %><br />
					<% if item.item_properties.where(:property_id => 6).first %>Количество мест: <%= item.item_properties.where(:property_id => 6).first.value  %><% end %></p>
            </li>
 			<% end %>
            </ul>
            <% if @page.pdf %><p class="file defaultPic"><a href="<%= @page.pdf.url %>">Каталог яхт</a>(5 Mб, ПДФ)</p><% end %>
			
			<p>
			
			<% unless current_user %><a class="invite" href="/register"><img alt="" src="/images/katalog_unreg.png" /></a>
			<% else %><a data-remote="true" class="invite" href="/messages/catalog_form/<%=current_user.id%>"><img alt="" src="/images/katalog.png" /></a><% end %>
			</p>			<% if @page.blocks.size > 0 %>
			<% @page.blocks.each do |block| %>
			<%= raw block.content %>
			<% end %>
			<% end %>
        </div>
        <div class="right">
        	<div class="part">
        		<img src="/images/ship.gif" alt="" /><a href="/about/sudovladelcu">Судовладельцу</a>
            	<img src="/images/cap.gif" alt="" /><a href="/about/kapitanu/">Капитану</a>
            </div>
            <h3><a href="/about/news">Новости</a></h3>
            <div class="news">
				<% @posts.each do |post| %>
				  <%= link_to post.title, "/about/news/#{post.id}" %><br/>
				<% end %>
            </div>
            <h3>Новое в <a href="/blogs">блоге</a></h3>
            <div class="news">
			    <% @blog_posts.each do |post| %>
				  <%= link_to post.title, blog_url(post) %><br/>
				<% end %>
            </div>
			
        </div>
        <div class="clear"></div>


</div>

app/views/home/owner.html.erb
<div class="w910 typical">
			<%= render 'shared/breadcrumbs' %>
<div class="left">
<%= render 'shared/left_menu' %>
</div>
<div class="right">
	<%= raw @page.body %>
	<a href="/filter" class="podborButton">Подобрать яхту<span></span></a>
	<h2>Резюме капитанов</h2>
	<ul class="resume">
		<% @resumes = Resume.order(:created_at).limit(4).all %>
		<% if @resumes %>
		<%  @resumes.each do |resume| %>
		<%= render 'resumes/resume', :resume => resume %>
		<% end %>
		<% end %>

		<li><a class="button" href="/about/resumes">Все капитаны</a></li>
	</ul>
</div>
</div>

app/views/home/show.html.erb
<% content_for :breadcrumbs do %>
/ <b><%= strip_tags(@page.title) %></b>
<% end %>
<h1><%= raw @page.title %></h1>
<%= raw @page.body %>

app/views/home/sitemap.html.erb
<div class="w910 fullSitemap">
	<div class="tree"><a href="/">Главная</a> / <b>Карта сайта</b> <div class="arrow"></div></div>
	<div class="clear"></div>
	<form action="#">
			<div class="text">
				<label class="search">
				<input type="text" value="Поиск" />
				</label>
			</div>
			<input class="submit formReady right" value="Найти " type="submit">
	</form>
	
	<div class="clear"></div>
	<a class="mainPage" href="/"><span></span>Главная страница</a>
	<div class="clear"></div>
	

	<div class="col_4">
		<ul>
			<% page = Page.find_by_slug('about') %>
			<li><a href="<%=page.url%>"><%= strip_tags(page.title) %></a></li>
			<ul>
			<% page.children.each do |page| %>
				<li><a href="<%=page.url%>"><%= strip_tags(page.title) %></a></li>
			<% end %>
			</ul>
		</ul>
	</div>
	<div class="col_4">
		<ul>
			<% page = Page.find_by_slug('catalog') %>
			<li><a href="<%=page.url%>"><%= strip_tags(page.title) %></a></li>
			<ul>
			<% page.children.each do |page| %>
				<li><a href="<%=page.url%>"><%= strip_tags(page.title) %></a></li>
			<% end %>
			</ul>
		</ul>
	</div>
	
	<div class="col_4">
		<ul>
			<% page = Page.find_by_slug('filter') %>
			<li><a href="<%=page.url%>"><%= strip_tags(page.title) %></a></li>
			<% page = Page.find_by_slug('events') %>
			<li><a href="<%=page.url%>"><%= strip_tags(page.title) %></a></li>
			<ul>
			<% page.children.each do |page| %>
				<li><a href="<%=page.url%>"><%= strip_tags(page.title) %></a></li>
			<% end %>
			</ul>
		</ul>
	</div>
	
	<div class="col_4">
		<ul>
			<li><a href="/blogs">Блог</a></li>
			<li><a href="/contacts">Контактная информация</a></li>
			<li><p>Карта сайта</p></li>
		</ul>
	</div>
</div>